name: Deploy

env:
  GCLOUD_ZONE: us-central1
  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}
  GKE_CLUSTER_NAME: cd-with-flux

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ env.GCLOUD_SA_KEY }}
          project_id: ${{ env.GCLOUD_PROJECT }}
          export_default_credentials: true

      - run: |-
          gcloud config set project $GCLOUD_PROJECT
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone "$GCLOUD_ZONE" --project $GCLOUD_PROJECT

      - name: Deploy API
        run: |
          cd $GITHUB_WORKSPACE
          ./deployments/deploy_bus.sh
